name: "Build"
on:
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest   # x86_64-linux
          - macos-15-intel  # x86_64-darwin
          - macos-latest    # aarch64-darwin
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - uses: canidae-solutions/lix-quick-install-action@v4

    - uses: cachix/cachix-action@v15
      with:
        name: pebble
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

    - name: Build pebble-tool
      run: nix build -L .#pebble-tool

    - name: Build pebble-qemu
      run: nix build -L .#pebble-qemu

    - name: Build pebble-toolchain-bin
      run: nix build -L .#pebble-toolchain-bin

    - name: Build pebbleEnv
      run: nix shell -f default.nix pebbleEnv --command sh -c "echo OK"

    - name: 'Build reverse dependency: no-time-for-this'
      run: |
        REPO=https://github.com/nilp0inter/no-time-for-this
        REV=45fa8581402955adc2b626a3f6509d8fa5701bb9
        git clone --depth=1 --revision "$REV" "$REPO" revdeps/no-time-for-this
        RDEP=path:revdeps/no-time-for-this
        nix build -L "$RDEP" --override-input pebble "$GITHUB_WORKSPACE"

    - name: 'Build reverse dependency: skunk'
      run: |
        REPO=https://github.com/unlobito/skunk
        REV=dcd7db99a408b5de2d988e6729ce0daaa70f6137
        git clone --depth=1 --revision "$REV" "$REPO" revdeps/skunk
        RDEP=revdeps/skunk/default.nix
        DIR=$GITHUB_WORKSPACE
        nix build -L --impure --expr "import $RDEP { pebbleDotNixSrc = $DIR; }"

    - name: 'Build reverse dependency: kijete'
      run: |
        REPO=https://github.com/yellowsink/kijete
        REV=4818aaf57add82666496fb56de37574cf88cdc66
        git clone --depth=1 --revision "$REV" "$REPO" revdeps/kijete
        RDEP=revdeps/kijete/default.nix
        DIR=$GITHUB_WORKSPACE
        nix build -L --impure --expr "import $RDEP { pebbleDotNixSrc = $DIR; }"
