name: "Build"
on:
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest # x86_64-linux
          - macos-13      # x86_64-darwin
          - macos-latest  # aarch64-darwin
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - uses: canidae-solutions/lix-quick-install-action@v3

    - uses: cachix/cachix-action@v15
      with:
        name: pebble
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

    - name: Build pebble-tool
      run: nix build -L .#pebble-tool

    - name: Build Core Devices pebble-tool
      run: nix build -L .#coredevices.pebble-tool

    - name: Build pebble-qemu
      run: nix build -L .#pebble-qemu

    - name: Build pebble-toolchain-bin
      run: nix build -L .#pebble-toolchain-bin

    - name: Build arm-embedded-toolchain
      if: ${{ matrix.os != 'macos-latest' }}
      run: nix build -L .#arm-embedded-toolchain

    - name: Build pebbleEnv
      run: nix shell -f default.nix pebbleEnv --command sh -c "echo OK"

    - name: Build pebbleEnv with Core Devices pebble-tool
      run: nix shell -f default.nix pebbleEnv --arg withCoreDevices true --command sh -c "echo OK"
